admin/jpbeta-admin-main.php
Instead of calling it Beta and Release Candidates when all of our internal language calls it "master" (or "master-stable") and "Beta", let's update this.
It gets confusing to have master-stable referred to as Beta, then talk about "Beta 1", which is actually a RC by the beta plugin language.
=> Use "Bleeding Edge" and "Tagged Beta"

admin/jpbeta-admin-main.php, jetpack-beta.php
Jetpack includes a Markdown module: let's use it to make the Testing list look better, include links, images, code snippets, and everything we want!
If the Markdown module isn't enabled, the list will be displayed anyway, but a notice will be displayed at the top of the page, inviting people to activate the module for a better display.
=> Beta Testing List: allow more formatting with Markdown

autoupdate-self.php, jetpack-beta-admin.php, jetpack-beta.php
Fixes #20
When installing the plugin via the zip file generated from GitHub,
the directory name is jetpack-beta-master. We should use that naming convention in the plugin as well.
=> Avoid errors when the plugin is installed manually.

jetpack-beta-admin.php
This will help with not losing the search context when clicking on one of the PRs links
* Makes the `more info` link when listing PRs in the autocomplete, open in a new window. Adds `target="_blank" rel="external noopener noreferrer"` to the link
=> Make the more info link for PRs open in new tab

jetpack-beta.php
Fixes #30
Currently all users can see the TopBar Node reading "Jetpack Beta" which links to Jetpack Beta settings page.
It's been reported that this does not look as an expected behaviour if you are not an administrator. 
* Makes the Topbar node not be a link if the user does not have update_plugins capabilities
**Before**
**After**
=> Admin: Make Topbar node not link to settings if user cannot update_plugins

class-jetpackbetaclicommand.php, jetpack-beta.php
Fixes #32
Introduces `wp jetpack-beta branch activate master` and `wp jetpack-beta branch activate stable` commands
=> Add wp cli command for activate master or stable branches

jetpack-beta.php
When deleting a plugin a could see this logged into debug.log
```
call_user_func_array() expects parameter 1 to be a valid callback, class 'Jetpack_Beta' does not have a method 'deleted_plugin'
```
and indeed, the method does not exist there even though we try to hook it.
=> Remove hook to deleted_plugin as de declared class method does not exist in Jetpack_Beta

jetpack-beta.php
1. Updates mail subjects to include site title or site url if site title is empty.
1. Bumps this plugins's  version to `2.1.1` in `jetpack-beta.php`.
Mails will look like this:
=> Add site title to mails subject

jetpack-beta.php
Add a check to make sure that at least the main jetpack.php file is present before procceding with the update of the jetpack plugin.
* Change the code in the new function to always thow the error. Not just when the file is not there. 
* change the file version of the master branch so that it needs an update. I did this using the wp-admin plugin editor. 
* using wp shell 
* run `Jetpack_Beta::run_autoupdate();` 
* Notice that the plugin doesn't update. 
* You should get no email. ( Do we want that ?)
=> Don't update the jetpack plugin if the build server errors.

admin/admin.css, admin/main.php, jetpack-beta-admin.php, jetpack-beta.php
Fixes #53 
Add a toggle that looks like 
The toggle doesn't show up if the autoupdates toggle is disabled or the constant defined. Since the toggle in those cases wouldn't do anything anyways.
This is what it looks like.
cc: @rickybanister and @oskosk
=> Add email notifications toggle

class-jetpackbetaclicommand.php, jetpack-beta.php
Right now it is not possible to install RC branches via cli command. This PR address this issue
To test: run `$wp jetpack-beta branch activate rc`
Make sure RC branch activated in Jetpack-beta plugin
=> Make it possible to install RC branches

jetpack-beta.php
This PR ensures that the version of Jetpack in use on account of the Jetpack Beta plugin is reported properly to/reflected in Calypso.
To test, apply this branch, ensure that the stable, release candidate, bleeding edge, and beta plugin deactivated versions all match in Calypso.
=> Jetpack Beta: Report correct Jetpack version to Calypso

jetpack-beta.php
This avoids fatal error in PHP < 5.5
```
Fatal error: Can't use function return value in write context in 
jetpack-beta/jetpack-beta.php on line 1039
```
* Updates an `empty()` usage by first assigning a return value from `get_bloginfo()` to a var and using `empty()` on the var instead. This fixes non-allowed usage of `empty()` for older version of PHP
* Bumps version to `2.2.1`.
=> Assign value to variable instead of checking with empty() on the return value.

class-jetpackbetaclicommand.php, jetpack-beta.php
* Updates code in `class-jetpackbetaclicommand.php` to be compatible with php 5.2.
* Bumps plugin version to 2.3
=> Make the cli code class be 5.2 compatible

jetpack-beta.php
It should fix fatals like this: `[02-Nov-2018 11:14:04] PHP Fatal error:  Cannot access empty property in /home/jptest/public_html/wp-content/plugins/jetpack-beta-master/jetpack-beta.php on line 540`
=> Fix fatal error in some cases

jetpack-beta.php
The constant `JETPACK_RC_API_URL` was once defined in 9388ee89f3cea86dad98e35f1975b870e9288f77 and never used in real life
=> Remove unused constant JETPACK_RC_API_URL

admin/admin.js, admin/main.php, jetpack-beta-admin.php
Fixes #74 
This PR adds Tracking to the toggles and branch activation buttons on the Jetpack Beta admin page.
Tracking only happens if one has accepted our ToS, and thus the tracking script is enqueued on that page.
1. Enable debug in your browser console: `localStorage.setItem( 'debug', 'dops:analytics' );`
2. Try clicking buttons on a site where Jetpack has never been connected to WordPress.com; you should see nothing.
3. Connect Jetpack to WordPress.com and reload the page.
4. Try clicking the buttons: you should see events being tracked: `jetpack_beta_toggle_autoupdates`, `jetpack_beta_toggle_email_notifications`, `jetpack_beta_activate_branch`, `jetpack_beta_submit_report`, with more details in event props.
5. Check Tracks for your username to see the events coming through.
=> Tracking: add tracking on the toggles, bug report submissions, and branch activation buttons

admin/admin.js, admin/main.php, jetpack-beta-admin.php, jetpack-beta.php
Fixes #83 
Fixes #66 
Adds a new search field for wp.org tags/trunk. 
It's not very DRY.  I ran into the classic "Should I refactor everything or copy/paste", and decided on the latter. I actually somewhat like the clear distinction between the two searches, even at the expense of some duplicate code. At the same time, maybe I'm just telling myself that because it's easier right now. Any way, I don't see us needing to expand this very often anyway. 
Test: 
- No console errors 
- Activating a stable tag or trunk should reflect properly in all UI
- Should not have any effect on any other selections from the Beta Manifest
- I've decided to hide the toggle when on a tag, so you should not expect to see it when active. 
- It downloads to the `jetpack` directory, as opposed to `jetpack-dev`. 
- …
=> Download tags directly from wp.org SVN

jetpack-beta.php
This PR adds plugin options to the Jetpack Sync whitelist via `jetpack_options_whitelist` filter
We should whitelist these options on WPCOM to make sure it works.  
Fixes #77 
WPCOM path: D30762-code
=> Add plugin options to sync whitelist

jetpack-beta.php
Fixes #79 
Saves all error output to the option using Jetpack::log.
Try to trigger errors when having this plugin installed. You can do something like this:
```
add_action( 'init', function() {
error_log( 'ADDING AN ERROR' );
$array = array();
error_log( $array['undefined offset'] );
})
```
You can see the error log using WP CLI like this:
```
$ wp option get jetpack_log
```
If you add this snippet outside Jetpack code, you won't see it in the error log, this is expected behaviour, because we are filtering the entries by a string match. To actually see the errors in the log, you can add the word `jetpack` into the array key we're trying to get in the code there^ 
```
error_log( $array['jetpack is bestpack'] );
```
This time you should be able to see the entry in the log.
=> Added a custom error handler that saves to Jetpack log.

jetpack-beta.php
Checks if the `vendor` directory is not empty before attempting to update to a new version of the branch that's currently active
1. Adds a check to see if the `vendor` dir is empty
2. Bumps version to  `2.4.1`.
=> Add check for empty vendor dir to block rogue updates if dependencies are mising

CHANGELOG.md, jetpack-beta-admin.php, jetpack-beta.php
This PR is a result of Automattic/Jetpack#15209 .
After switching to another branch that's not "current", compared to the "old" branch that we switch out of, can see warnings or errors in the error log. 
This happens because we continue executing actions and shutdown handlers after the code on the filesystem is changed and this causes a desync in what it's supposed to do. 
This PR adds a forced `exit()` after we redirect the user back to WP-Admin after the new branch has been put in place and options updated to make sure those actions and handlers are not executed and no errors are triggered.
Since this relies on specific conditions to be met, generic testing is a bit hard.
For the moment it would work with the following instructions:
* Activate `Bleeding edge` Jetpack
* After it's …
=> Switching to Live branch: Prevent code from executing after new code has been put in place.

jetpack-beta.php
Both the `jetpack` and `jetpack-dev` plugin paths can be added to the autoloader's plugin paths cache if the user switches between stable and development versions. This can result in undesirable behavior, including fatals. The autoloader will see both the `jetpack` and `jetpack-dev` plugins as active and will use the `jetpack` plugin's packages
when `jetpack-dev` is active. This happens because the autoloader prefers stable package versions.
Fix this by clearing the autoloader's plugin paths cache when the Jetpack version is changed.
1. Activate the stable version of Jetpack.
2. Activate the `fix / autoloader inclusion` branch.
3. See a fatal.
1. Repeat the steps above. The fatal should not be generated.
=> Clear the autoloader plugin cache when the Jetpack version is changed
